services:
  php:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    environment:
      PHP_IDE_CONFIG: "serverName=symfony"
      XDEBUG_MODE: "debug"
      XDEBUG_CLIENT_HOST: "host.docker.internal"
    volumes:
      - ./:/var/www
      - ./docker/dev/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/dev/php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini

  nginx:
    ports:
      - "8000:80"

  postgresql:
    ports:
      - "5432:5432"
