services:
  nginx:
    image: nginx:1.25-alpine
    restart: unless-stopped
    depends_on:
      - php
    volumes:
      - ./public:/var/www/html/public:ro
      - ./docker/prod/nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M

  php:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    restart: unless-stopped
    environment:
      APP_ENV: prod
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/${POSTGRES_DB}
    volumes:
      - ./:/var/www/html:ro
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

  postgresql:
    image: postgres:15.5-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
